---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 彭文宇.
--- DateTime: 2025-04-12 17:49
---
-- 所有的键,即商品id
local keys=KEYS
-- 值
local value=ARGV[1]
-- 过期时间
local expireTime=ARGV[2]
for i, key in ipairs(keys) do
  local result= redis.call("SETNX",key,value)
    if result==0 then
   --加锁失败 释放前面已经加上的锁
        for j=1,i-1  do
            redis.call('DEL', KEYS[j])
        end
        return 0
    end
    redis.call("EXPIRE",key,expireTime)
end
return 1