---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 彭文宇.
--- DateTime: 2025-04-12 20:14
--- 用于释放锁时的原子性
local keys=KEYS

local value=ARGV[1]

for _, key in ipairs(keys) do
    if redis.call("GET",key)==value then
        --说明当前锁是自己持有的,允许释放锁
        redis.call("DEL",key)
    end
end
return 0